version: '3.8'

services:
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env/.env.dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:root_password
      - MYSQL_DATABASE:DEV
      - MYSQL_USER:USER
      - MYSQL_PASSWORD:PASSWORD
    ports:
      - 3306:3306

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
    
  # celery_worker:
  #   build: ./backend
  #   command: celery -A backend worker --loglevel=info
  #   env_file:
  #     - ./backend/.env/.env.dev
  #   volumes:
  #     - ./backend:/usr/src/app/
  #   depends_on:
  #     - api
  #     - redis
  
  # celery_beat:
  #   build: ./backend
  #   command: celery -A backend beat --loglevel=info
  #   env_file:
  #     - ./backend/.env/.env.dev
  #   volumes:
  #     - ./backend:/usr/src/app/
  #   depends_on:
  #     - api
  #     - redis

  # flower:
  #   build: ./backend
  #   command: celery -A backend flower
  #   env_file:
  #     - ./backend/.env/.env.dev
  #   ports:
  #     - "5555:5555"
  #   volumes:
  #     - ./backend:/usr/src/app/
  #   depends_on:
  #     - api
  #     - redis

volumes:
  mysql_data:
