version: '3.8'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env/.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

volumes:
  postgres_data:
  static_volume:
  media_volume:
